/**
 * Chrónos icons — shim backed by lucide-react so the app compiles.
 * Replace with the full proprietary SVG set when available.
 */
export {
  Home,
  Search,
  Users,
  UserPlus,
  UserCheck,
  UserX,
  User,
  MessageCircle,
  Bell,
  Film,
  Plus,
  Compass,
  Heart,
  Share2 as Share,
  Bookmark,
  Eye,
  TrendingUp,
  Link2,
  Camera,
  Image,
  ImagePlus,
  Music,
  MapPin,
  Mic,
  Wallet,
  Gift,
  Settings,
  Shield,
  Lock,
  KeyRound,
  LogOut,
  LogIn,
  ArrowLeft,
  ArrowUpRight,
  ArrowDownLeft,
  Check,
  CheckCircle2,
  ChevronRight,
  Clock,
  Download,
  Upload,
  FileText,
  HelpCircle,
  Loader2,
  Mail,
  Minus,
  Moon,
  Monitor,
  Palette,
  Pause,
  Maximize,
  Pencil,
  Play,
  Send,
  Smartphone,
  Trash2,
  Volume2,
  VolumeX,
  X,
  XCircle,
  Zap,
  AlertTriangle,
  Accessibility,
  Megaphone,
  BarChart3,
  Phone,
  Copy,
  MoreHorizontal,
  QrCode,
  Receipt,
  Store,
  ShoppingBag,
  ShoppingCart,
  Star,
  Tag,
  Package,
  Filter,
  Truck,
  Video,
  Sliders,
  AtSign,
  Crop,
  RotateCw as RotateRight,
  RotateCcw as RotateLeft,
  FlipHorizontal,
  FlipVertical,
  Type as TypeTool,
  Brush,
  Undo2 as Undo,
  Redo2 as Redo,
  Sun,
  Contrast,
  Droplet,
  Thermometer,
  Eraser,
  Coins as ChronosCoin,
  Store as Marketplace,
  MessageCircle as Comment,
  Smile as Emoji,
  Radio as Live,
  Users as Groups,
  Newspaper as Articles,
  BarChart2 as Polls,
  Headphones as Audio,
  Coins as Earnings,
  Banknote as Withdraw,
  BadgeCheck as Verified,
  Sparkles as Premium,
  Megaphone as Promotions,
  BarChart3 as Stats,
  Globe,
  Flag as Report,
  Ban as Block,
  Twitter,
  Facebook,
  Send as Telegram,
  MessageCircle as Whatsapp,
  Repeat2 as Repost,
  BarChart2 as PollBars,
  Frame as FrameTool,
  Aperture as Sharpen,
  CircleDot as BlurTool,
  Focus as Vignette,
} from "lucide-react";
